### ISSUE TITLE
How is the cost_s/maxspeed_forward column calculated

### ISSUE THREAD

**Issue by Stophface** [pgRouting/osm2pgrouting#163]
I have two questions regarding the rules the columns in the `ways` table are created

1. How is the `cost_s` column in `osm2pgrouting` is calculated? Are that `seconds`? Seconds of what? Is it the traveltime and the speed to calculate the traveltime is used from `maxspeed_forward`

2. How does `osm2pgrouting` create the `maxspeed_forward` column in the `ways` table?
2.1 Is the number extracted from the `key:maxspeed` https://wiki.openstreetmap.org/wiki/Key:maxspeed ? 
2.2 How does it treat different units (`mph` and `kmh`). 
2.3 If there is no value in `key:maxspeed`, what numbers/value will it insert?

**Comment by cvvergara** [comment]
1.1) https://github.com/pgRouting/osm2pgrouting/blob/master/src/Export2DB.cpp#L460
1.2) _s  is for seconds

2.1) yes, if it exists otherwise  uses the default value of maxspeed in the configuration file you are using
2.2) by converting to km/hr: https://github.com/pgRouting/osm2pgrouting/blob/master/src/Way.cpp#L248
2.3) the default value of maxspeed in the configuration file you are using

**Comment by Stophface** [comment]
Awesome, thanks. 
Unfortunately my C++ is not good enough to derive these information from the code. Thats why I asked here. Would be nice to have that on the docs somewhere.
