### ISSUE TITLE
64bit OSM id

### ISSUE THREAD

**Issue by manutor1** [pgRouting/osm2pgrouting#220]
Hi,

The Osm2pgrouting wiki page announces that this program does not work well anymore : 
"This plugin no longer works correctly with current OSM data, as it internally converts object ID's to signed int, and truncation to 32-bit occurs during import to a PostGIS database, causing unexpected overwrites or breaking geometries of unrelated objects. See 64-bit Identifiers for more information."
_source : https://wiki.openstreetmap.org/wiki/Osm2pgrouting_
Is that bug already corrected ?

Best regards,

Emmanuel

**Comment by cayetanobv** [comment]
Hi @manutor1 ,

This is not true because OSM ID's are inserted to PostgreSQL database as [bigint data type](https://www.postgresql.org/docs/current/static/datatype-numeric.html). This data type is a large-range integer (8 bytes) which can holds OSM ID's 64 bit range: -9223372036854775808 to +9223372036854775807.

There are two old issues related to this problem:
- https://github.com/pgRouting/osm2pgrouting/issues/16
- https://github.com/pgRouting/osm2pgrouting/issues/60

I think we need to change OSM wiki page: https://wiki.openstreetmap.org/wiki/Osm2pgrouting

@pgRouting/admins  what do you think about it?

Thanks,

**Comment by dkastl** [comment]
I updated the OSM Wiki and removed the false warning. Thank you for the notice!

**Comment by cayetanobv** [comment]
Thanks @dkastl . I have also updated this page from OSM wiki related to software and how they handle 64 bit OSM ID's:
https://wiki.openstreetmap.org/wiki/64-bit_Identifiers

I close again the issue.
