### ISSUE TITLE
Program Options: -- help

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/osm2pgrouting#54]
` -h -- help`
specifics: help should show also if an unknown/required or any  parameter is wrong, the help message should be displayed. 
Component of issue: #43

**Comment by cvvergara** [comment]
Because --host -h is for Host,
for the help only use --help

**Comment by dkastl** [comment]
Well, I thought what about looking at how @psql@ and @osm2psql@ do, but unfortunately they do differently. I think following one of them is a good idea, because then users will feel familiar with the program options:

#### psql

```
       -h hostname
       --host=hostname
           Specifies the host name of the machine on which the server is running. If the value begins
           with a slash, it is used as the directory for the Unix-domain socket.
       -?
       --help
           Show help about psql command line arguments, and exit.
```

#### osm2psql

```
       -H|--host hostname
              Database server hostname or socket location.
       -h|--help
              Help information.
              Add -v to display supported projections.
```

Not sure, which one looks better. So for me any is fine.

**Comment by cvvergara** [comment]
Removed the -h of the title becausse its used as a shortcut for --host
